### ISSUE TITLE
Please setup the output to "English"

### ISSUE THREAD

**Issue by Tikam02** [nashsu/FreeAskInternet#33] opened 2024-04-09 19:13 UTC
## The output chats are in chinese

![image](https://github.com/nashsu/FreeAskInternet/assets/10548085/3a3bd050-688e-474e-b6a5-266dbe46141c)

**Comment by ibrahimkettaneh** [comment] 2024-04-10 04:55
I would like to boost this

**Comment by ibrahimkettaneh** [comment] 2024-04-10 04:57
duplicate of #16

**Comment by nashsu** [comment] 2024-04-10 09:52
Just update, add new UI interface, you can set response language, and custom LLM setting.

**Closed by nashsu** 2024-04-10 09:52 UTC
